AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template
Parameters:
  myVPCs: 
    Description: Amazon VPCs
    Type: "AWS::EC2::VPC::Id"
  mySubnets: 
    Description: Amazon Subnets
    Type: "List<AWS::EC2::Subnet::Id>"
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  IAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SSMRoletoEC2
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - 
          Ref: IAMRole

  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup
      ImageId: ami-0947d2ba12ee1ff75
      SubnetId: !ImportValue ExPrivateSubnet1
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: MyTestEC2-01
        - Key: Project
          Value: internalpoc
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22 and 443
      VpcId: !ImportValue MyVPCTest
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: !Ref SSHLocation
        - IpProtocol: icmp
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: !Ref SSHLocation
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - AvailabilityZone
  IAMRole:
    Value: !Ref IAMRole
    Export:
      Name: ExpIAMRole
  InstanceProfile:
    Value: !Ref InstanceProfile
    Export:
      Name: ExpInstanceProfile
  InstanceSecurityGroup:
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: ExpInstanceSecurityGroup
