AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  EC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      SecurityGroupIds: 
        - !ImportValue ExpInstanceSecurityGroup
      ImageId: ami-0947d2ba12ee1ff75
      SubnetId: !ImportValue ExPrivateSubnet2
      IamInstanceProfile: !ImportValue ExpInstanceProfile
      Tags:
        - Key: Name
          Value:
            'Fn::Join':
              - '-'
              - - Ref: 'AWS::StackName'
                - MyEC2
        - Key: Project
          Value: internalpoc
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2Instance
      - AvailabilityZone