---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPC:
    Description: 'Please enter the EKS VPC'
    Type: String   
  EKSSubnetId1:
    Description: 'Please enter the public EKS SubnetId1'
    Type: String 
  EKSSubnetId2:
    Description: 'Please enter the public EKS SubnetId2'
    Type: String 
Resources:  
  VPCESecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      SecurityGroupIngress:
      - IpProtocol: tcp
        CidrIp: 10.192.0.0/0
        FromPort: 443
        ToPort: 443
      VpcId: !Ref VPC   
  ECRAPIEndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      # PrivateDnsEnabled: true
      SubnetIds: 
        - !Ref EKSSubnetId1
        - !Ref EKSSubnetId2        
      VpcEndpointType: Interface
      SecurityGroupIds: 
      - !Ref VPCESecurityGroup
      VpcId: !Ref VPC 
  ECRDKREndpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      # PrivateDnsEnabled: true
      SubnetIds: 
        - !Ref EKSSubnetId1
        - !Ref EKSSubnetId2        
      VpcEndpointType: Interface
      SecurityGroupIds: 
      - !Ref VPCESecurityGroup
      VpcId: !Ref VPC   
  S3Endpoint:
    Type: 'AWS::EC2::VPCEndpoint'
    Properties:
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref VPC   
