AWSTemplateFormatVersion: 2010-09-09
Description: Template creates Interface Endpoints in 2 AZs with EIPs listening on a TCP port 
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Customer Name or (OU Name)
        Parameters:
          - Name
      - Label:
          default: Networking Configuration
        Parameters:
          - VPC
          - ConsumerAccountSubnets
      - Label:
          default: Endpoint Details
        Parameters:
          - EndpointServiceName
Parameters:
  Name:
    Description: Enter Customer Name or OU Name (REQUIRED)
    Type: String
    AllowedPattern: ".+"
  VPC:
    Type: 'AWS::EC2::VPC::Id'
  ConsumerAccountSubnets:
    Description: Consumer Account Filebeat Subnets. Ensure the subnets are in atleast two AZ's
    Type: 'List<AWS::EC2::Subnet::Id>'
  EndpointServiceName:
    Description: Enter Endpoint Service Name obtained from the Provider (REQUIRED)
    Type: String
    AllowedPattern: ".+"

Resources:
  InterfaceEndpointSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable VPCEndpoint Access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '9094'
          ToPort: '9094'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC

  InterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      VpcId: !Ref VPC
      VpcEndpointType: Interface
      ServiceName: !Ref EndpointServiceName
      PrivateDnsEnabled: false
      SubnetIds: !Ref ConsumerAccountSubnets
      SecurityGroupIds: 
        - !Ref InterfaceEndpointSecurityGroup

  SSMCustomerName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /ebt/${Name}/customerName
      Type: String
      Value: !Ref Name
  SSMVPCEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /ebt/${Name}/vpcEndpointDns
      Type: String
      Value: !Select 
      - 1
      - !Split 
        - ':'
        - !Select
          - 0
          - !GetAtt 
            - InterfaceEndpoint
            - DnsEntries

Outputs:
  InterfaceEndpontID:
    Description: Interface Endpoint ID
    Value: !Ref InterfaceEndpoint